// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-modules.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { modules } from "npm:@/data/quizData";
var list_modules_default = defineTool({
  name: "list_modules",
  title: "List training modules",
  description: "List all T3P training modules (Taxi, VTC, VMDTR) with their sub-modules and question counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const summary = modules.map((m) => ({
      id: m.id,
      name: m.name,
      description: m.description,
      subModules: m.subModules.map((s) => ({
        id: s.id,
        name: s.name,
        questionCount: s.questionCount
      }))
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { modules: summary }
    };
  }
});

// src/lib/mcp/tools/get-module-questions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
import { officialQuestions as questions } from "npm:@/data/quizData";
var get_module_questions_default = defineTool2({
  name: "get_module_questions",
  title: "Get questions for a module",
  description: "Return official T3P quiz questions for a given module id (e.g. 'taxi', 'vtc', 'vmd', 'trans'). Question text, options and reference are returned; correct answers are not exposed.",
  inputSchema: {
    moduleId: z.string().min(1).describe("Module id, e.g. 'taxi' or 'vtc'."),
    subModuleId: z.string().optional().describe("Optional sub-module id to filter within the module."),
    limit: z.number().int().min(1).max(200).optional().describe("Max questions to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ moduleId, subModuleId, limit }) => {
    let list = questions.filter((q) => q.moduleId === moduleId);
    if (subModuleId) list = list.filter((q) => q.subModuleId === subModuleId);
    if (limit) list = list.slice(0, limit);
    const safe = list.map((q) => ({
      id: q.id,
      moduleId: q.moduleId,
      subModuleId: q.subModuleId,
      text: q.text,
      options: q.options,
      reference: q.reference,
      difficulty: q.difficulty
    }));
    return {
      content: [{ type: "text", text: `Returned ${safe.length} questions.` }],
      structuredContent: { questions: safe }
    };
  }
});

// src/lib/mcp/tools/get-my-progress.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_progress_default = defineTool3({
  name: "get_my_progress",
  title: "Get my quiz progress",
  description: "Return the signed-in user's quiz results (module, score, total, taken_at) ordered by most recent.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("quiz_results").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(100);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Fetched ${data?.length ?? 0} quiz results.` }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-badges.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_badges_default = defineTool4({
  name: "get_my_badges",
  title: "Get my badges",
  description: "Return the signed-in user's earned badges.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("user_badges").select("*").eq("user_id", ctx.getUserId()).order("earned_at", { ascending: false });
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Fetched ${data?.length ?? 0} badges.` }],
      structuredContent: { badges: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "myawyyumhghbctvtnhkv";
var mcp_default = defineMcp({
  name: "t3p-quest-mcp",
  title: "T3P Quest MCP",
  version: "0.1.0",
  instructions: "Tools for T3P Quest, a French T3P (Taxi/VTC/VMDTR) exam prep app. Use `list_modules` and `get_module_questions` to explore official training content. Use `get_my_progress` and `get_my_badges` to read the signed-in user's data.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_modules_default, get_module_questions_default, get_my_progress_default, get_my_badges_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
