// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-modules.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/data/quizData.ts
var modules = [
  // MODULES COMMUNS
  {
    id: "reglementation",
    name: "A. R\xE9glementation du T3P",
    description: "\xC9preuve A \u2014 R\xE9glementation du transport public particulier de personnes",
    type: "commun",
    icon: "\u{1F4CB}",
    color: "module-reglementation",
    rsCode: "A",
    subModules: [
      { id: "reg-1", name: "Conditions d'acc\xE8s \xE0 la profession", description: "Conditions et modalit\xE9s d'acc\xE8s", questionCount: 15 },
      { id: "reg-2", name: "Obligations professionnelles", description: "Droits et devoirs du conducteur", questionCount: 12 },
      { id: "reg-3", name: "R\xE9glementation nationale", description: "Lois et d\xE9crets applicables", questionCount: 18 }
    ]
  },
  {
    id: "securite",
    name: "C. S\xE9curit\xE9 routi\xE8re",
    description: "\xC9preuve C \u2014 S\xE9curit\xE9 routi\xE8re : pr\xE9vention des risques et conduite s\xE9curitaire",
    type: "commun",
    icon: "\u{1F6E1}\uFE0F",
    color: "module-securite",
    rsCode: "C",
    subModules: [
      { id: "sec-1", name: "Code de la route", description: "R\xE8gles de circulation", questionCount: 20 },
      { id: "sec-2", name: "Pr\xE9vention des accidents", description: "Risques et comportements", questionCount: 15 },
      { id: "sec-3", name: "Premiers secours", description: "Gestes de premiers secours", questionCount: 10 }
    ]
  },
  {
    id: "gestion",
    name: "B. Gestion",
    description: "\xC9preuve B \u2014 Gestion : gestion d'entreprise et obligations comptables",
    type: "commun",
    icon: "\u{1F4CA}",
    color: "module-gestion",
    rsCode: "B",
    subModules: [
      { id: "ges-1", name: "Comptabilit\xE9 de base", description: "Notions comptables essentielles", questionCount: 20 },
      { id: "ges-2", name: "Fiscalit\xE9", description: "Obligations fiscales", questionCount: 10 },
      { id: "ges-3", name: "Gestion d'entreprise", description: "Cr\xE9ation et gestion", questionCount: 10 }
    ]
  },
  {
    id: "francais",
    name: "D. Langue fran\xE7aise",
    description: "\xC9preuve D \u2014 Capacit\xE9 d'expression et de compr\xE9hension en langue fran\xE7aise",
    type: "commun",
    icon: "\u{1F1EB}\u{1F1F7}",
    color: "module-francais",
    rsCode: "D",
    subModules: [
      { id: "fra-1", name: "Compr\xE9hension \xE9crite", description: "Lecture et analyse de textes", questionCount: 20 },
      { id: "fra-2", name: "Expression \xE9crite", description: "R\xE9daction professionnelle", questionCount: 20 }
    ]
  },
  {
    id: "anglais",
    name: "E. Langue anglaise",
    description: "\xC9preuve E \u2014 Capacit\xE9 d'expression et de compr\xE9hension en anglais (niveau A2 CECRL)",
    type: "commun",
    icon: "\u{1F1EC}\u{1F1E7}",
    color: "module-anglais",
    rsCode: "E",
    subModules: [
      { id: "ang-1", name: "Vocabulaire professionnel", description: "Termes du transport", questionCount: 20 },
      { id: "ang-2", name: "Conversation client", description: "Dialogues courants", questionCount: 20 },
      { id: "ang-3", name: "Tourisme international", description: "Vocabulaire et dialogues touristiques", questionCount: 20 },
      { id: "ang-4", name: "Phrases types & situations", description: "Expressions cl\xE9s par situation", questionCount: 20 }
    ]
  },
  // MODULES SPÉCIFIQUES
  {
    id: "taxi",
    name: "F(T). Territoire et r\xE9glementation locale (Paris)",
    description: "\xC9preuve F(T) \u2014 Connaissance du territoire et r\xE9glementation locale : ADS, tarifs et maraude \xE0 Paris",
    type: "specifique",
    icon: "\u{1F695}",
    color: "module-taxi",
    rsCode: "F(T)",
    rsFiche: "RS5635",
    subModules: [
      { id: "tax-1", name: "ADS & exploitation Paris", description: "Autorisation de stationnement et r\xE8gles de la Pr\xE9fecture de Police", questionCount: 11 },
      { id: "tax-2", name: "Tarifs Paris 2026", description: "Tarifs A/B/C/D, forfaits a\xE9roports et suppl\xE9ments parisiens", questionCount: 10 },
      { id: "tax-3", name: "Maraude & stationnement 75", description: "Zones de prise en charge, stations, voies de bus et ZFE", questionCount: 9 }
    ]
  },
  {
    id: "vtc",
    name: "F(V) + G(V). Sp\xE9cifique VTC",
    description: "\xC9preuves F(V) et G(V) \u2014 D\xE9veloppement commercial, gestion propre et r\xE9glementation nationale VTC",
    type: "specifique",
    icon: "\u{1F697}",
    color: "module-vtc",
    rsCode: "F(V) + G(V)",
    rsFiche: "RS5637",
    subModules: [
      { id: "vtc-1", name: "Carte professionnelle VTC", description: "Conditions et renouvellement", questionCount: 20 },
      { id: "vtc-2", name: "R\xE9servation pr\xE9alable", description: "Obligations de r\xE9servation", questionCount: 10 },
      { id: "vtc-3", name: "Obligations VTC", description: "R\xE8gles sp\xE9cifiques VTC", questionCount: 11 }
    ]
  },
  {
    id: "vmdtr",
    name: "F(M) + G(M). Sp\xE9cifique VMDTR",
    description: "\xC9preuves F(M) et G(M) \u2014 S\xE9curit\xE9 moto, r\xE9glementation, passager et d\xE9veloppement commercial",
    type: "specifique",
    icon: "\u{1F3CD}\uFE0F",
    color: "module-vmdtr",
    rsCode: "F(M) + G(M)",
    rsFiche: "RS5636",
    subModules: [
      { id: "vmd-securite", name: "F(M) \u2013 S\xE9curit\xE9 moto", description: "Accidentologie, dynamique, conduite pr\xE9ventive, entretien", questionCount: 8 },
      { id: "vmd-reglementation", name: "F(M) \u2013 R\xE9glementation VMDTR", description: "Carte pro, r\xE9servation pr\xE9alable, v\xE9hicules, signal\xE9tique", questionCount: 8 },
      { id: "vmd-passager", name: "G(M) \u2013 Prise en charge passager", description: "Consignes, peur, EPI, comportement de la moto", questionCount: 8 },
      { id: "vmd-commercial", name: "G(M) \u2013 D\xE9veloppement commercial", description: "Marketing, fid\xE9lisation, communication, partenaires", questionCount: 8 }
    ]
  },
  {
    id: "taxi-national",
    name: "G(T). R\xE9glementation taxi (nationale et Paris)",
    description: "\xC9preuve G(T) \u2014 R\xE9glementation nationale taxi et gestion propre \xE0 l'activit\xE9",
    type: "specifique",
    icon: "\u{1F696}",
    color: "module-taxi",
    rsCode: "G(T)",
    rsFiche: "RS5635",
    subModules: [
      { id: "tx75-nat", name: "R\xE9glementation nationale", description: "Code des transports et lois applicables \xE0 tous les taxis", questionCount: 10 },
      { id: "tx75-loc", name: "R\xE9glementation locale", description: "Arr\xEAt\xE9s pr\xE9fectoraux et r\xE8gles sp\xE9cifiques au d\xE9partement", questionCount: 10 },
      { id: "tx75-pra", name: "Pratique professionnelle", description: "Tarification, \xE9quipements et exercice quotidien", questionCount: 10 }
    ]
  },
  {
    id: "taxi-territoire",
    name: "F(T). Connaissance du territoire (Paris)",
    description: "\xC9preuve F(T) \u2014 Connaissance du territoire d'exercice : monuments, gares, h\xF4pitaux, axes majeurs",
    type: "specifique",
    icon: "\u{1F5FC}",
    color: "module-taxi",
    rsCode: "F(T)",
    rsFiche: "RS5635",
    subModules: [
      { id: "topo-mon", name: "Monuments & Sites touristiques", description: "Lieux embl\xE9matiques et attractions", questionCount: 10 },
      { id: "topo-gar", name: "Gares & Transports", description: "Gares SNCF, routi\xE8res et a\xE9roports", questionCount: 10 },
      { id: "topo-hop", name: "H\xF4pitaux & Services", description: "\xC9tablissements de sant\xE9 et services publics", questionCount: 10 },
      { id: "topo-axe", name: "Axes & Circulation", description: "Boulevards, places et itin\xE9raires", questionCount: 10 }
    ]
  },
  // Module Relation Client (nouveau)
  {
    id: "relation-client",
    name: "Relation client (transversal)",
    description: "Comp\xE9tences transversales aux \xE9preuves : accueil, communication et gestion des situations difficiles",
    type: "commun",
    icon: "\u{1F91D}",
    color: "module-relation",
    subModules: [
      { id: "rel-1", name: "Accueil et service", description: "Qualit\xE9 d'accueil client", questionCount: 20 },
      { id: "rel-2", name: "Communication", description: "Communication professionnelle", questionCount: 20 }
    ]
  }
];

// src/lib/mcp/tools/list-modules.ts
var list_modules_default = defineTool({
  name: "list_modules",
  title: "List training modules",
  description: "List all T3P training modules (Taxi, VTC, VMDTR) with their sub-modules and question counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const summary = modules.map((m) => ({
      id: m.id,
      name: m.name,
      description: m.description,
      subModules: m.subModules.map((s) => ({
        id: s.id,
        name: s.name,
        questionCount: s.questionCount
      }))
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { modules: summary }
    };
  }
});

// src/lib/mcp/tools/get-module-questions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var getEnv = (name) => globalThis.Deno?.env.get(name);
var get_module_questions_default = defineTool2({
  name: "get_module_questions",
  title: "Get questions for a module",
  description: "Return official T3P quiz questions for a given module id (e.g. 'taxi', 'vtc', 'vmdtr'). Questions are read from the database (single source of truth); correct answers are not exposed.",
  inputSchema: {
    moduleId: z.string().min(1).describe("Module id, e.g. 'taxi' or 'vtc'."),
    subModuleId: z.string().optional().describe("Optional sub-module id to filter within the module."),
    limit: z.number().int().min(1).max(200).optional().describe("Max questions to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ moduleId, subModuleId, limit }) => {
    const supabaseUrl = getEnv("SUPABASE_URL");
    const serviceKey = getEnv("SUPABASE_SERVICE_ROLE_KEY");
    if (!supabaseUrl || !serviceKey) {
      return {
        content: [
          { type: "text", text: "Questions unavailable: database credentials missing in this environment." }
        ],
        structuredContent: { questions: [] }
      };
    }
    const params = new URLSearchParams({
      select: "id,module_id,sub_module_id,text,option_a,option_b,option_c,option_d,reference,difficulty",
      module_id: `eq.${moduleId}`,
      order: "id.asc",
      limit: String(limit ?? 200)
    });
    if (subModuleId) params.set("sub_module_id", `eq.${subModuleId}`);
    const response = await fetch(`${supabaseUrl}/rest/v1/questions?${params.toString()}`, {
      headers: { apikey: serviceKey, Authorization: `Bearer ${serviceKey}` }
    });
    if (!response.ok) {
      return {
        content: [{ type: "text", text: `Failed to load questions (HTTP ${response.status}).` }],
        structuredContent: { questions: [] }
      };
    }
    const rows = await response.json();
    const safe = rows.map((q) => ({
      id: q.id,
      moduleId: q.module_id,
      subModuleId: q.sub_module_id,
      text: q.text,
      options: [
        { letter: "A", text: q.option_a },
        { letter: "B", text: q.option_b },
        { letter: "C", text: q.option_c },
        { letter: "D", text: q.option_d }
      ],
      reference: q.reference,
      difficulty: q.difficulty
    }));
    return {
      content: [{ type: "text", text: `Returned ${safe.length} questions.` }],
      structuredContent: { questions: safe }
    };
  }
});

// src/lib/mcp/tools/get-my-progress.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_progress_default = defineTool3({
  name: "get_my_progress",
  title: "Get my quiz progress",
  description: "Return the signed-in user's quiz results (module, score, total, taken_at) ordered by most recent.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("quiz_results").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(100);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Fetched ${data?.length ?? 0} quiz results.` }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-badges.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_badges_default = defineTool4({
  name: "get_my_badges",
  title: "Get my badges",
  description: "Return the signed-in user's earned badges.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("user_badges").select("*").eq("user_id", ctx.getUserId()).order("earned_at", { ascending: false });
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Fetched ${data?.length ?? 0} badges.` }],
      structuredContent: { badges: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "myawyyumhghbctvtnhkv";
var mcp_default = defineMcp({
  name: "t3p-quest-mcp",
  title: "T3P Quest MCP",
  version: "0.1.0",
  instructions: "Tools for T3P Quest, a French T3P (Taxi/VTC/VMDTR) exam prep app. Use `list_modules` and `get_module_questions` to explore official training content. Use `get_my_progress` and `get_my_badges` to read the signed-in user's data.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_modules_default, get_module_questions_default, get_my_progress_default, get_my_badges_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
